replicaCount: 1
env: dev

image:
  repository: europe-west1-docker.pkg.dev/msgb-bt-7-2026/boutique-dev/redis-cart
  digest: "sha256:0000000000000000000000000000000000000000000000000000000000000000"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  port: 6379
  targetPort: 6379

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
