apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boutique.fullname" . }}
  labels:
    {{- include "boutique.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "boutique.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boutique.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "boutique.serviceAccountName" . }}
      securityContext:
        {{- include "boutique.podSecurityContext" . | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: {{ include "boutique.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "boutique.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "boutique.selectorLabels" . | nindent 6 }}
{{- end }}
