{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "boutique.serviceAccountName" . }}
  labels:
    {{- include "boutique.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ . | quote }}
  {{- end }}
{{- end }}
