env: dev

image:
  repository: europe-west1-docker.pkg.dev/msgb-bt-7-2026/boutique-dev/currencyservice
  digest: "sha256:8058133095e281ea9bbdac444153f0a5d3aa3c82e51b593dea66d362c85635f1"

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
