env: dev

image:
  repository: europe-west1-docker.pkg.dev/msgb-bt-7-2026/boutique-dev/frontend
  digest: "sha256:359f2bb111a200c3f8b974222911ba82ac0e5364faaecc8f7fa2db382b2d6016"

containerSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

gateway:
  host: dev.biroltilki.art
