env: dev

image:
  repository: europe-west1-docker.pkg.dev/msgb-bt-7-2026/boutique-dev/frontend
  digest: "sha256:6d890a6c370591fac87a4986ec98e1508aff863b8e73cb3cc62f89bdf5cc13f0"

gateway:
  host: dev.biroltilki.art
