env: dev

image:
  repository: europe-west1-docker.pkg.dev/msgb-bt-7-2026/boutique-dev/currencyservice
  digest: "sha256:3ba3198c9fe76a4004e045bd7eb920259668843dc357f13649777139950e8f22"

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
