name: CI productcatalogservice

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/productcatalogservice/**"
      - "charts/productcatalogservice/**"
      - ".github/workflows/reusable-service-ci.yml"
      - ".github/workflows/ci-productcatalogservice.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service: productcatalogservice
    secrets:
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_BUILD_SA: ${{ secrets.GCP_BUILD_SA }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
