name: CI redis-cart

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/redis-cart/**"
      - "charts/redis-cart/**"
      - ".github/workflows/reusable-service-ci.yml"
      - ".github/workflows/ci-redis-cart.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service: redis-cart
    secrets:
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_BUILD_SA: ${{ secrets.GCP_BUILD_SA }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
